//BOOK ENDPOINTS

### Create a new book ###
POST http://localhost:3000/api/books
Content-Type: application/json

{
 "title": "Sample Book 2",
  "author": "Sam Ndambuki",
  "price": 29.99,
  "quantity_in_stock": 50,
  "description": "An example book",
  "published_year": 2023,
  "genre": "Fiction"
}

### Get all books ###
GET http://localhost:3000/api/books


### Get one book ###
GET http://localhost:3000/api/books/1


//USER ENDPOINTS
### Register User ###
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username":"testing",
  "email":"testing@gmail.com",
  "password":"N10234424008s"
}

